[manifest]
id = "mod_fs"
display_name = "Mod Filesystem"
description =  """
A library providing APIs for replacing and adding assets via the game's filesystem.
"""
short_description = "Lets mods replace and add game filesystem assets."

version = "0.1.0"
authors = [ "Shinx121" ]

game_id = "dino-planet"
minimum_recomp_version = "0.1.0"

dependencies = [
# Example dependency:
#    "modname:1.0.0"
]

native_libraries = [
# Example native library:
#    { name = "my_native_library", funcs = ["my_native_library_function"] }
]

[inputs]
elf_path = "build/mod.elf"
mod_filename = "mod_fs"
func_reference_syms_file = "../lib/dino-recomp-mod-api/dino.syms.toml"
data_reference_syms_files = [
    "../lib/dino-recomp-mod-api/dino.datasyms.toml", 
    "../lib/dino-recomp-mod-api/dino.datasyms_manual.toml", 
    "../dino.datasyms_extra.toml"
]
additional_files = [ ]
