[manifest]
id = "shinx121_misc"
display_name = "Shinx121's Miscellaneous Mod"
description =  """
Various mods of mine that are either experiments or haven't been made into their own dedicated mods yet.
"""
short_description = "My misc mods."

version = "0.1.0"
authors = [ "Shinx121" ]

game_id = "dino-planet"
minimum_recomp_version = "0.1.0"

dependencies = [
    "mod_fs:0.1.0"
]

native_libraries = [
# Example native library:
#    { name = "my_native_library", funcs = ["my_native_library_function"] }
]

[inputs]
elf_path = "build/mod.elf"
mod_filename = "shinx121_misc"
func_reference_syms_file = "../lib/dino-recomp-mod-api/dino.syms.toml"
data_reference_syms_files = [
    "../lib/dino-recomp-mod-api/dino.datasyms.toml", 
    "../lib/dino-recomp-mod-api/dino.datasyms_manual.toml", 
    "../dino.datasyms_extra.toml"
]
additional_files = [ ]
